# This Dockerfile is used to build the image cloudwicklabs/verticals:2.0
FROM python:3.9.18-slim-bookworm
LABEL maintainer="devops@cloudwick.com"

RUN apt-get update && apt-get -y upgrade && apt-get install -y wget uuid-runtime jq unzip docker.io

# Install node.js 18
RUN mkdir /usr/local/nvm
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 18.20.0
RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default \
    && npm install -g yarn

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

# Install awscli v2
RUN wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O "awscliv2.zip" && \
    unzip awscliv2.zip && \
    rm awscliv2.zip && ./aws/install

# Install boto3
RUN python -m pip install boto3
RUN apt-get install -y pwgen

SHELL ["/bin/bash", "-c"]
