{
 "title": "Amorphic Data Platform Backend Services Statistics",
 "description": "This dashboard displays Amorphic backbone backend services statistics like Lambda invocations, throttles, durations and StateMachines success vs failures.",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Lambda Functions Statistics Over Time Period Selected",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Average Execution Time of All Lambda Functions",
   "type": "timeseries",
   "description": "This panel describes the average execution time taken by all lambda functions combined",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top 4 Lambda Function Invocations [3 hours window]",
   "type": "timeseries",
   "description": "This Panel Illustrates Top 4 Lambda Functions Invoked Maximum Time.\nThere is a limitation - This panel could only show data of last 3 hours",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "metricName": "Invocations",
     "metricQueryType": 1,
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/Lambda", "type": "functionParameter" },
        { "name": "FunctionName", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "groupBy": {
       "expressions": [
        { "property": { "name": "FunctionName", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "limit": 4,
      "orderBy": { "name": "SUM", "type": "function" },
      "orderByDirection": "DESC",
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "Invocations", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(Invocations) FROM SCHEMA(\"AWS/Lambda\", FunctionName) GROUP BY FunctionName ORDER BY SUM() DESC LIMIT 4",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda Invocations & Throttles [Including APIs, DataLoads, Async Calls and Scheduled Events]",
   "type": "timeseries",
   "description": "This panel describes the total invocations of the lambda functions with throttling including all invocations of lambda from async calls, scheduled events, apis etc.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "metricName": "Throttles",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "State Machine Stats Include API, Async, Data loads, Scheduled Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Successful Executions",
   "type": "timeseries",
   "description": "This panel describes how successful State Machine executed",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "dimensions": { "StateMachineArn": "*" },
     "expression": "SELECT SUM(\"ExecutionsSucceeded\")\nFROM SCHEMA(\"AWS/States\", \"StateMachineArn\")",
     "metricName": "ExecutionsSucceeded",
     "metricQueryType": 1,
     "namespace": "AWS/States",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/States", "type": "functionParameter" },
        { "name": "StateMachineArn", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "ExecutionsSucceeded", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(ExecutionsSucceeded) FROM SCHEMA(\"AWS/States\", StateMachineArn)",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Failed Executions",
   "type": "timeseries",
   "description": "This panel describes how state machines executed failed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "dimensions": { "StateMachineArn": "*" },
     "expression": "SELECT SUM(\"ExecutionsSucceeded\")\nFROM SCHEMA(\"AWS/States\", \"StateMachineArn\")",
     "metricName": "ExecutionsFailed",
     "metricQueryType": 1,
     "namespace": "AWS/States",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/States", "type": "functionParameter" },
        { "name": "StateMachineArn", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "ExecutionsFailed", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(ExecutionsFailed) FROM SCHEMA(\"AWS/States\", StateMachineArn)",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Average Time Duration State Machine Took",
   "type": "timeseries",
   "description": "This panel describes how much time duration all state machines take",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "StateMachineArn": "*" },
     "expression": "SELECT SUM(\"ExecutionsSucceeded\")\nFROM SCHEMA(\"AWS/States\", \"StateMachineArn\")",
     "metricName": "ExecutionTime",
     "metricQueryType": 1,
     "namespace": "AWS/States",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/States", "type": "functionParameter" },
        { "name": "StateMachineArn", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "ExecutionTime", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(ExecutionTime) FROM SCHEMA(\"AWS/States\", StateMachineArn)",
     "statistic": "Sum"
    }
   ]
  }
 ]
}