{
 "title": "Amorphic Data Platform Infrastructure",
 "description": "This dashboard displays Amorphic core infrastructure statistics like Squid Proxy & Trace Servers CPU & Memory utilization.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "squid_proxy_logs", "query": "${VAR_SQUID_PROXY_LOGS}" }
  ]
 },
 "panels": [
  {
   "title": "Squid Proxy Tunnel Stats Over Time Period Selected",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Squid Proxy Status Success vs Failures",
   "type": "gauge",
   "description": "This panel shows the count of each tunnel status in the Squid proxy",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message, @logStream, @log\n| parse @message /^(?<timestamp>[^\\s]+) {1,}(?<elapsed>[^\\s]+) {1,}(?<remote_host>[^\\s]+) {1,}(?<result_code>[^\\s]+)/ \n| filter result_code = \"TCP_TUNNEL/200\"\n| stats count(*) as Success",
     "logGroups": [
      { "arn": "$squid_proxy_logs", "name": "$squid_proxy_logs" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "fields @timestamp, @message, @logStream, @log\n| parse @message /^(?<timestamp>[^\\s]+) {1,}(?<elapsed>[^\\s]+) {1,}(?<remote_host>[^\\s]+) {1,}(?<result_code>[^\\s]+)/ \n| filter result_code != \"TCP_TUNNEL/200\"\n| stats count(*) as Failures",
     "logGroups": [
      { "arn": "$squid_proxy_logs", "name": "$squid_proxy_logs" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Squid Proxy Requests Failures vs Success Over Time Period Selected",
   "type": "timeseries",
   "description": "This panel displays the count of requests with a specific tunnel status over 10-minute intervals",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "expression": "fields @timestamp, @message, @logStream, @log \n| parse @message /^(?<timestamp>[^\\s]+) {1,}(?<elapsed>[^\\s]+) {1,}(?<remote_host>[^\\s]+) {1,}(?<result_code>[^\\s]+)/ \n| filter result_code = \"TCP_TUNNEL/200\"\n| stats count(*) as Success by bin(10m)",
     "logGroups": [
      { "arn": "$squid_proxy_logs", "name": "$squid_proxy_logs" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin(10m)" ]
    },
    {
     "expression": "fields @timestamp, @message, @logStream, @log \n| parse @message /^(?<timestamp>[^\\s]+) {1,}(?<elapsed>[^\\s]+) {1,}(?<remote_host>[^\\s]+) {1,}(?<result_code>[^\\s]+)/ \n| filter result_code != \"TCP_TUNNEL/200\"\n| stats count(*) as Failures by bin(10m)",
     "logGroups": [
      { "arn": "$squid_proxy_logs", "name": "$squid_proxy_logs" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin(10m)" ]
    }
   ]
  },
  {
   "title": "EC2 Servers CPU Utilization",
   "type": "timeseries",
   "description": "This Panel Displays the CPU Utilization of EC2 servers installed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expression": "100-$A", "type": "math" },
    { "expression": "100-$B", "type": "math" }
   ]
  },
  {
   "title": "EC2 Servers Memory Utilization",
   "type": "timeseries",
   "description": "This Panel displays Memory Percent Utilization of EC2 Servers Installed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dimensions": { "InstanceName": "SquidProxyInstance" },
     "label": "Squid Proxy Instance",
     "metricName": "MemoryUsedPercent",
     "namespace": "CWAgent",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceName": "GrafanaInstance" },
     "label": "Grafana Instance",
     "metricName": "MemoryUsedPercent",
     "namespace": "CWAgent",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}