{
 "title": "Amorphic Data Platform Supporting Services Statistics",
 "description": "This dashboard displays other multiple supporting services statistics like LLM Models latency & invocations, DMS Latencies at source and target, total number of service resources utilized.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "regional_waf_logs", "query": "${VAR_REGIONAL_WAF_LOGS}" },
   { "name": "global_waf_logs", "query": "${VAR_GLOBAL_WAF_LOGS}" }
  ]
 },
 "panels": [
  {
   "title": "GenAI LLM Model Statistics Over Time Period Selected",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Invocations Count",
   "type": "timeseries",
   "description": "This panel displays total number of invocations over period of time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dimensions": { "ModelId": "*" },
     "metricName": "Invocations",
     "namespace": "AWS/Bedrock",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Invocations Latency",
   "type": "timeseries",
   "description": "This panel displays latency on invocations over period of time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "ModelId": "*" },
     "metricName": "InvocationLatency",
     "namespace": "AWS/Bedrock",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Regional WAF Requests",
   "type": "geomap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expression": "fields httpRequest.country |\n stats count(*) as requestCount by httpRequest.country",
     "logGroups": [
      { "arn": "$regional_waf_logs", "name": "$regional_waf_logs" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "httpRequest.country" ]
    }
   ]
  },
  {
   "title": "Global WAF Requests",
   "type": "geomap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expression": "fields httpRequest.country |\n stats count(*) as requestCount by httpRequest.country",
     "logGroups": [
      { "arn": "$global_waf_logs", "name": "$global_waf_logs" }
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statistic": "Average",
     "statsGroups": [ "httpRequest.country" ]
    }
   ]
  },
  { "title": "Data Ingestion (Bulk Load)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CDC Latency At Source During Ingestion",
   "type": "timeseries",
   "description": "This panel describes CDC latency at source during ingestion time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": {
      "ReplicationInstanceIdentifier": "*",
      "ReplicationTaskIdentifier": "*"
     },
     "metricName": "CDCLatencySource",
     "namespace": "AWS/DMS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CDC Latency At Target During Ingestion",
   "type": "timeseries",
   "description": "This panel describes CDC latency at target during ingestion time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": {
      "ReplicationInstanceIdentifier": "*",
      "ReplicationTaskIdentifier": "*"
     },
     "metricName": "CDCLatencyTarget",
     "namespace": "AWS/DMS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Total Number of AWS Service Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "DMSSubnetGroups",
     "namespace": "Custom/AWSServiceUsage",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "metricName": "DynamoDBTables",
     "namespace": "Custom/AWSServiceUsage",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "metricName": "IAMRoles",
     "namespace": "Custom/AWSServiceUsage",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "metricName": "LambdaConcurrency",
     "namespace": "Custom/AWSServiceUsage",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "metricName": "NotebookInstances",
     "namespace": "Custom/AWSServiceUsage",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "metricName": "S3Buckets",
     "namespace": "Custom/AWSServiceUsage",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "metricName": "SSMParameters",
     "namespace": "Custom/AWSServiceUsage",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}