# AWS Official python3.12 lambda base image
FROM public.ecr.aws/lambda/python:3.12

LABEL maintainer="amorphic-support@cloudwick.com"

ENV lambda_layer_modules_src_dir="/var/lang/lib/python3.12/site-packages/"

RUN dnf update -y \
  && dnf -y install gcc postgresql-devel

# Copy the requirements file to download the libraries
COPY ai/api/lambda-layer/requirements.txt ./
RUN python3 -m pip install -r requirements.txt

SHELL ["/bin/bash", "-c"]